all: 
	gcc -Xlinker -rpath=/home/osboxes/ROPWorkshop/rop_exercises/02_demo -Xlinker -I/home/osboxes/ROPWorkshop/rop_exercises/02_demo/ld-linux-x86-64.so.2 02_demo_64_bit.c -fno-stack-protector -no-pie -O0 -o 02_demo_64_bit

